name: Build and Deploy to AWS EC2
 
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Docker build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.IMAGE_NAME }}:latest

      - name: Docker pull image & run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_INSTANCE_IP }}
          username: ${{ secrets.AWS_INSTANCE_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo docker stop sparkles-container || true
            sudo docker rm sparkles-container || true
            sudo docker pull ${{ secrets.IMAGE_NAME }}:latest
            sudo docker run -d --name sparkles-container -p 8080:8080 --env-file ./.env ${{ secrets.IMAGE_NAME }}:latest
